# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

GC=/usr/local/go/bin/go
CXX=/usr/bin/gcc
CU=/usr/bin/clang
MXX=/usr/bin/gcc
MM=/usr/bin/gcc
CC=/usr/bin/gcc
RC=/home/r3tr0/.cargo/bin/rustc
AS=/usr/bin/gcc

RCSH=/home/r3tr0/.cargo/bin/rustc
SH=/usr/bin/g++
GCLD=/usr/local/go/bin/go
RCLD=/home/r3tr0/.cargo/bin/rustc
LD=/usr/bin/g++
GCAR=/usr/local/go/bin/go
AR=/usr/local/bin/ar
RCAR=/home/r3tr0/.cargo/bin/rustc

echeck_CCFLAGS=-m64 -fvisibility=hidden -O3 -Isrc/include -O2 -DNDEBUG
echeck_LDFLAGS=-m64 -s -O2

default:  echeck

all:  echeck

.PHONY: default all  echeck

echeck: build/linux/x86_64/release/echeck
build/linux/x86_64/release/echeck: build/.objs/echeck/linux/x86_64/release/src/view.c.o build/.objs/echeck/linux/x86_64/release/src/main.c.o build/.objs/echeck/linux/x86_64/release/src/utils.c.o build/.objs/echeck/linux/x86_64/release/src/elf.c.o build/.objs/echeck/linux/x86_64/release/src/macho.c.o
	@echo linking.release echeck
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/echeck build/.objs/echeck/linux/x86_64/release/src/view.c.o build/.objs/echeck/linux/x86_64/release/src/main.c.o build/.objs/echeck/linux/x86_64/release/src/utils.c.o build/.objs/echeck/linux/x86_64/release/src/elf.c.o build/.objs/echeck/linux/x86_64/release/src/macho.c.o $(echeck_LDFLAGS) > build/.build.log 2>&1

build/.objs/echeck/linux/x86_64/release/src/view.c.o: src/view.c
	@echo compiling.release src/view.c
	@mkdir -p build/.objs/echeck/linux/x86_64/release/src
	@$(CC) -c $(echeck_CCFLAGS) -o build/.objs/echeck/linux/x86_64/release/src/view.c.o src/view.c > build/.build.log 2>&1

build/.objs/echeck/linux/x86_64/release/src/main.c.o: src/main.c
	@echo compiling.release src/main.c
	@mkdir -p build/.objs/echeck/linux/x86_64/release/src
	@$(CC) -c $(echeck_CCFLAGS) -o build/.objs/echeck/linux/x86_64/release/src/main.c.o src/main.c > build/.build.log 2>&1

build/.objs/echeck/linux/x86_64/release/src/utils.c.o: src/utils.c
	@echo compiling.release src/utils.c
	@mkdir -p build/.objs/echeck/linux/x86_64/release/src
	@$(CC) -c $(echeck_CCFLAGS) -o build/.objs/echeck/linux/x86_64/release/src/utils.c.o src/utils.c > build/.build.log 2>&1

build/.objs/echeck/linux/x86_64/release/src/elf.c.o: src/elf.c
	@echo compiling.release src/elf.c
	@mkdir -p build/.objs/echeck/linux/x86_64/release/src
	@$(CC) -c $(echeck_CCFLAGS) -o build/.objs/echeck/linux/x86_64/release/src/elf.c.o src/elf.c > build/.build.log 2>&1

build/.objs/echeck/linux/x86_64/release/src/macho.c.o: src/macho.c
	@echo compiling.release src/macho.c
	@mkdir -p build/.objs/echeck/linux/x86_64/release/src
	@$(CC) -c $(echeck_CCFLAGS) -o build/.objs/echeck/linux/x86_64/release/src/macho.c.o src/macho.c > build/.build.log 2>&1

clean:  clean_echeck

clean_echeck: 
	@rm -rf build/linux/x86_64/release/echeck
	@rm -rf build/linux/x86_64/release/echeck.sym
	@rm -rf build/.objs/echeck/linux/x86_64/release/src/view.c.o
	@rm -rf build/.objs/echeck/linux/x86_64/release/src/main.c.o
	@rm -rf build/.objs/echeck/linux/x86_64/release/src/utils.c.o
	@rm -rf build/.objs/echeck/linux/x86_64/release/src/elf.c.o
	@rm -rf build/.objs/echeck/linux/x86_64/release/src/macho.c.o

